### ISSUE TITLE
add `module.exports = nextConfig` to next.config.js

### ISSUE THREAD

**Issue by laura-webber** [replicate/getting-started-nextjs#11]
I had to add

`module.exports = nextConfig`

to the bottom of the `next.config.js` file in order to get the demo app to work. Otherwise, it threw the [no exported configuration found](https://nextjs.org/docs/messages/empty-configuration) error in the terminal and a runtime error in the DOM 
![CleanShot 2023-04-24 at 11 39 33@2x](https://user-images.githubusercontent.com/93733302/234086541-d25b01f5-a849-4102-b719-70a415573f66.png)

**Comment by zeke** [comment]
Hey thanks for reporting. 

I'm not sure how you encountered this issue, as the `module.exports = nextConfig` line you mentioned is present in the file and [has been for some time](https://github.com/replicate/getting-started-nextjs/blob/0e04f0acf14321f0d67ed811a570562db238a9f9/next.config.js#L18).

I'm going to go ahead and close this, but please let me know if I'm missing something.
